### PR TITLE
Perform bdwgc checkout with --force

### PR DESCRIPTION
**Pull request by bcardiff**
Workaround for https://github.com/ivmai/bdwgc/pull/317

### CODE REVIEW

**Comment by bcardiff** [comment]
Checking build on https://circleci.com/workflow-run/e0fc41b7-644f-4cf3-ba68-9fdbc2178795

**Comment by ivmai** [comment]
> Workaround for ivmai/bdwgc#317

I've fixed it.

**Comment by bcardiff** [comment]
Thanks @ivmai

**Comment by RX14** [comment]
Is this still required or are we trying to use a release with the bad commit?

**Comment by bcardiff** [comment]
No longer needed since master of bdwgc is not longer conflicting the process. 

I noticed it is a duplicate of #52. We can rebase that and merge it since there it is an improvement after all.

**Pull request closed without merging**
