### PR TITLE
Remove libatomic_ops dependency

### PR DESCRIPTION
**Pull request by straight-shoota**
libatomic_ops is no longer required for building bdwgc starting with 8.0.0. We're using newer versions now, so there's no need to pull in libatomic_ops.

### CODE REVIEW

**Comment by straight-shoota** [comment]
CI running at https://app.circleci.com/pipelines/github/crystal-lang/crystal?branch=ci%2Fremove-libatomic_ops

**Review by beta-ziliani — APPROVED** [review]
🚀  it feels so good to remove a dependency!

**Comment by straight-shoota** [comment]
CI shows a lot of failures. Most of them are unrelated to this PR (#145, and the known issues with i386 and alpine).

I don't know what's going on with the `dist_linux` job: https://app.circleci.com/pipelines/github/crystal-lang/crystal/6937/workflows/721b58ad-2c44-432e-998f-580b2c579f57/jobs/64226

```
Step 7/17 : RUN curl https://ftp.pcre.org/pub/pcre/pcre-${libpcre_version}.tar.gz | tar -zx  && cd pcre-${libpcre_version}  && ./configure --disable-shared --disable-cpp --enable-jit --enable-utf --enable-unicode-properties  && make -j$(nproc)
 ---> Running in 0526008b18b2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   162  100   162    0     0    285      0 --:--:-- --:--:-- --:--:--   285

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c curl https://ftp.pcre.org/pub/pcre/pcre-${libpcre_version}.tar.gz | tar -zx  && cd pcre-${libpcre_version}  && ./configure --disable-shared --disable-cpp --enable-jit --enable-utf --enable-unicode-properties  && make -j$(nproc)' returned a non-zero code: 2
make: *** [build/bundled-libs.tar] Error 2
```

Looks like the download is failing. I can't reproduce that locally. But it appears to be consistens in CI.

**Comment by beta-ziliani** [comment]
maybe the name of the branch is a problem for macOS?
```
The `version' component of Mac package names can only include alphabetical characters (a-z, A-Z), numbers (0-9), dots  (.), plus signs (+), and dashes (-). Converting `ci-remove-libatomic_ops-dev' to `ci-remove-libatomic-ops-dev
```

**Comment by straight-shoota** [comment]
I added a change to fix the branch name sanitation: https://github.com/crystal-lang/crystal/commit/ca0db735114da3d18710cf6c2724e7b821c4021a

Now the previously failing CI jobs succeed: https://app.circleci.com/pipelines/github/crystal-lang/crystal/6981/workflows/94c27061-f6c0-4e12-b58b-252c9a03c39d

Thanks for the pointers :+1:

**Comment by straight-shoota** [comment]
Integration workflow is still all geen: https://app.circleci.com/pipelines/github/crystal-lang/crystal/7602/workflows/445f6074-771e-4a44-9264-253cdcd9c6c0

**Pull request merged**
